openapi: 3.0.3

info:
  title: mock-tim-custom-jwt-userinfo API
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/license/mit/

servers:
  - url: https://ruuter.test.buerokratt.ee

paths:
  /mock-tim-custom-jwt-userinfo:
    post:
      summary: Return a mocked JWT user info object
      responses:
        '200':
          description: Successfully returned the mocked JWT user info object
          content:
            application/json:
              schema:
                type: object
                properties:
                  sub:
                    type: string
                  firstName:
                    type: string
                    example: "MARY ÄNN"
                  idCode:
                    type: string
                    example: "EE60001019906"
                  displayName:
                    type: string
                    example: "MARY ÄNN"
                  iss:
                    type: string
                    example: "test.buerokratt.ee"
                  exp:
                    type: integer
                    format: int64
                    example: 1670250948
                  login:
                    type: string
                    example: "EE60001019906"
                  iat:
                    type: integer
                    format: int64
                    example: 1670243748
                  jti:
                    type: string
                    example: "e14a5084-3b30-4a55-8720-c2ee22f43c2c"
                  authorities:
                    type: array
                    items:
                      type: string
                      example: "ROLE_ADMINISTRATOR"