openapi: 3.1.0
info:
  title: Estimated user waiting time
  description: API for calculating chat duration and estimated waiting time.
  version: 1.0.0
servers:
  - url: https://play.buerokratt.ee
    description: main server for the database requests
paths:
  /estimated-waiting-time:
    get:
      summary: Get estimated waiting time for the response
      parameters:
        - name: id
          in: query
          description: id of the chat
          schema:
            type: string
            example: 8cfbc32a-7244-4933-8a25-14422b557ad2
      responses:
        '200':
          description: Estimated waiting time of the chat
          content:
            application/json:
              schema:
                type: object
                properties:
                  estimatedWaitingTime:
                    type: number
                    example: 100
        '400':
          description: No chatId in the request parameter
          content:
            application/json:
              schema:
                type: object
                properties:
                  returnNoParameter:
                    type: string
                    example: '300'
