openapi: 3.1.0
info:
  title: Get organization working time
  description: API that returns the working time of an organization
  version: 1.0.0
servers:
  - url: https://play.buerokratt.ee
    description: main server for the database requests
paths:
  /get-organization-working-time:
    get:
      summary: get organization working time
      responses:
        '200':
          description: return emergency responseData
          content:
            application/json:
              schema:
                type: object
                properties:
                  organizationWorkingTimeData:
                    type: string
        '400':
          description: not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  returnNotFound:
                    type: string
                    example: 'error: not found'