openapi: 3.0.3

info:
  title: get-organization-working-time API
  description: API that returns the working time of an organization
  version: 1.0.0

servers:
  - url: https://ruuter.test.buerokratt.ee
    description: Main server for the database requests

paths:
  /get-organization-working-time:
    get:
      summary: Send a request for organization working time
      responses:
        '200':
          description: Return emergency response data
          content:
            application/json:
              schema:
                type: object
                properties:
                  organizationWorkingTimeData:
                    type: string
        '400':
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  returnNotFound:
                    type: string
                    example: 'error: not found'