openapi: 3.1.0
info:
  title: Openapi specification for GET get-emergency-notice API
  description: API that returns a emergency response when a valid one exists
  version: 1.0.0
servers:
  - url: https://play.buerokratt.ee
    description: Main server for the database requests
paths:
  /get-emergency-notice:
    get:
      summary: Send a request for emergency response when a valid one exists
      responses:
        '200':
          description: Return emergency responseData
          content:
            application/json:
              schema:
                type: object
                properties:
                  emergencyNoticeData:
                    type: object
