openapi: 3.0.3

info:
  title: get-widget-config API
  description: API for getting widget config
  version: 1.0.0
  license:
    name: MIT
    url: https://github.com/buerokratt/Ruuter/blob/main/LICENSE

servers:
  - url: https://ruuter.test.buerokratt.ee
    description: Main server for the database requests

paths:
  /get-widget-config:
    get:
      summary: Send a request for widget config
      responses:
        '200':
          description: Return widget config
          content:
            application/json:
              schema:
                type: object
                properties:
                  widgetConfigData:
                    type: object
        '400':
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  returnNotFound:
                    type: string
                    example: 'error: not found'