openapi: 3.0.3

info:
  title: estimated-waiting-time API
  description: API for calculating chat duration and estimated waiting time.
  version: 1.0.0
  license:
    name: MIT
    url: https://github.com/buerokratt/Ruuter/blob/main/LICENSE

servers:
  - url: https://ruuter.test.buerokratt.ee
    description: Main server for the database requests

paths:
  /get-estimated-waiting-time:
    get:
      summary: Get estimated waiting time for the response
      parameters:
        - name: id
          in: query
          description: Id of the chat
          schema:
            type: string
            example: '8cfbc32a-7244-4933-8a25-14422b557ad2'
      responses:
        '200':
          description: Estimated waiting time of the chat
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      return_first_estimated_time_from_array:
                        type: object
                        properties:
                          isActive:
                            type: boolean
                            example: true
                          time:
                            type: string
                            example: '1'
                  error:
                    example: null