openapi: 3.1.0
info:
  title: Get a emergency response
  description: API that returns a emergency response when a valid one exists
  version: 1.0.0
servers:
  - url: https://play.buerokratt.ee
    description: main server for the database requests
paths:
  /get-emergency-notice:
    get:
      summary: get a emergency response when a valid one exists
      responses:
        '200':
          description: return emergency responseData
          content:
            application/json:
              schema:
                type: object
                properties:
                  emergencyNoticeData:
                    type: object
