openapi: 3.0.3

info:
  title: label-history API
  version: 1.0.0
  license:
    name: MIT
    url: https://github.com/buerokratt/Ruuter/blob/main/LICENSE

servers:
  - url: https://ruuter.test.buerokratt.ee

paths:
  /label-history:
    post:
      summary: Add labels to the chat history
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                labels:
                  type: array
                  items:
                    type: string
                  description: Array of labels
                chatId:
                  type: string
                  description: The chat ID
              required:
                - labels
                - chatId
      responses:
        '200':
          description: Successfully added the labels
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    description: Response from inserting chat history labels
        '401':
          description: Unauthorized - user does not have the required ROLE_ADMINISTRATOR
          content:
            text/plain:
              schema:
                type: string
                example: "error: unauthorized"

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: customJwtCookie

security:
  - cookieAuth: []