openapi: 3.0.3

info:
  title: cs-get-widget-config API
  description: YAML file defining an endpoint for settings of the widget
  version: 1.0.0
  license:
    name: MIT
    url: https://github.com/buerokratt/Ruuter/blob/main/LICENSE

servers:
  - url: https://ruuter.test.buerokratt.ee

paths:
  /cs-get-widget-config:
    get:
      summary: Checks whether user is authorized and retrieves configuration of the widget
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  widgetProactiveSeconds:
                    type: integer
                    example: 3
                  widgetDisplayBubbleMessageSeconds:
                    type: integer
                    example: 5
                  widgetBubbleMessageText:
                    type: string
                    example: 'Küsi minult!'
                  widgetColor:
                    type: string
                    example: '#E99B03'
                  isWidgetActive:
                    type: boolean
                    example: true
        '401':
          description: Unauthorized request

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: customJwtCookie

security:
  - cookieAuth: []