openapi: 3.1.0

info:
  title: Openapi specification for cs-get-csa-name-visibility API
  description: YAML file defining an endpoint for retrieving visibility settings for csa name if the end user is an administrator
  version: 1.0.0

servers:
  - url: https://play.buerokratt.ee

paths:
  /cs-get-csa-name-visibility:
    get:
      summary: checks whether user has administrator access and retrieves the name visibility setting for csa
#      parameters:
#        - in: header
#          name: cookie
#          schema:
#            type: string
#          required: true
#          description: Cookie containing user information
      responses:
        '200':
          description: csa name visibility retrieved successfully
          content:
            application/json:
              schema:
                object
        '401':
          description: Unauthorized request

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: customJwtCookie

security:
  - cookieAuth: []