openapi: 3.0.3

info:
  title: cs-get-emergency-notice API
  description: YAML file defining an endpoint for retrieving emergency notice data
  version: 1.0.0
  license:
    name: MIT
    url: https://github.com/buerokratt/Ruuter/blob/main/LICENSE

servers:
  - url: https://ruuter.test.buerokratt.ee

paths:
  /cs-get-emergency-notice:
    get:
      summary: Checks whether user has administrator access and retrieves the emergency notice
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  emergencyNoticeText:
                    type: string
                    example: 'Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean lacinia bibendum nulla sed consectetur.'
                  emergencyNoticeStartISO:
                    type: string
                    format: date-time
                    example: '2023-05-30T00:00:00Z'
                  emergencyNoticeEndISO:
                    type: string
                    format: date-time
                    example: '2023-05-30T00:00:00Z'
                  isEmergencyNoticeVisible:
                    type: boolean
                    example: true
        '401':
          description: Unauthorized request

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: customJwtCookie

security:
  - cookieAuth: []