openapi: 3.0.3

info:
  title: cs-get-user-profile-settings API
  description: YAML file defining an endpoint for retrieving the user profile settings
  version: 1.0.0
  license:
    name: MIT
    url: https://github.com/buerokratt/Ruuter/blob/main/LICENSE

servers:
  - url: https://ruuter.test.buerokratt.ee

paths:
  /cs-get-user-profile-settings:
    get:
      summary: Checks whether user is authorized and retrieves profile settings of the user
      #Openapi 3 does not allow requestBody for a GET operation, maybe find an alternative (for example POST operation) or keep as is
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: The ID of the user
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: integer
                    example: 1
                  forwardedChatPopupNotifications:
                    type: boolean
                    example: true
                  forwardedChatSoundNotifications:
                    type: boolean
                    example: true
                  forwardedChatEmailNotifications:
                    type: boolean
                    example: true
                  newChatPopupNotifications:
                    type: boolean
                    example: true
                  newChatSoundNotifications:
                    type: boolean
                    example: true
                  newChatEmailNotifications:
                    type: boolean
                    example: true
                  useAutocorrect:
                    type: boolean
                    example: false
        '401':
          description: Unauthorized request

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: customJwtCookie

security:
  - cookieAuth: []