openapi: 3.0.3

info:
  title: cs-get-customer-support-agents API
  description: YAML file for getting the customer support agents
  version: 1.0.0
  license:
    name: MIT
    url: https://github.com/buerokratt/Ruuter/blob/main/LICENSE

servers:
  - url: https://ruuter.test.buerokratt.ee

paths:
  /cs-get-customer-support-agents:
    get:
      summary: Get list of customer support agents
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    login:
                      type: string
                      example: Anne Clowd
                    firstName:
                      type: string
                      nullable: true
                    lastName:
                      type: string
                      nullable: true
                    idCode:
                      type: string
                      example: EE49002124277
                    displayName:
                      type: string
                      example: Anne Clowd
                    authorities:
                      type: array
                      items:
                        type: string
                      example: [ "ROLE_ADMINISTRATOR", "ROLE_SERVICE_MANAGER", "ROLE_CUSTOMER_SUPPORT_AGENT", "ROLE_CHATBOT_TRAINER", "ROLE_ANALYST" ]
                    csaTitle:
                      type: string
                      example: nõustaja
                    customerSupportStatus:
                      type: string
                      example: idle
        '401':
          description: Unauthorized request

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: customJwtCookie

security:
  - cookieAuth: []