openapi: 3.0.3

info:
  title: cs-get-organization-working-time API
  description: YAML file defining an endpoint for retrieving the working time of the organization
  version: 1.0.0
  license:
    name: MIT
    url: https://github.com/buerokratt/Ruuter/blob/main/LICENSE

servers:
  - url: https://ruuter.test.buerokratt.ee

paths:
  /cs-get-organization-working-time:
    get:
      summary: Checks whether user is authorized and retrieves the working time of the organization
      responses:
        '200':
          description: Organization working time data retrieved successfully
          content:
            application/json:
              schema:
                type: object
        '401':
          description: Unauthorized request

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: customJwtCookie

security:
  - cookieAuth: []