openapi: 3.1.0

info:
  title: Openapi specification for cs-get-widget-config API
  description: YAML file defining an endpoint for settings of the widget
  version: 1.0.0

servers:
  - url: https://play.buerokratt.ee

paths:
  /cs-get-widget-config:
    get:
      summary: Checks whether user is authorized and retrieves configuration of the widget
      responses:
        '200':
          description: Widget configuration retrieved successfully
          content:
            application/json:
              schema:
                type: object
        '401':
          description: Unauthorized request

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: customJwtCookie

security:
  - cookieAuth: []