openapi: 3.1.0

info:
  title: Openapi specification for cs-get-emergency-notice API
  description: YAML file defining an endpoint for retrieving emergency notice data
  version: 1.0.0

servers:
  - url: https://play.buerokratt.ee

paths:
  /cs-get-emergency-notice:
    get:
      summary: checks whether user has administrator access and retrieves the title visibility setting for csa
      #      parameters:
      #        - in: header
      #          name: cookie
      #          schema:
      #            type: string
      #          required: true
      #          description: Cookie containing user information
      responses:
        '200':
          description: csa title visibility retrieved successfully
          content:
            application/json:
              schema:
                object
        '401':
          description: Unauthorized request

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: customJwtCookie

security:
  - cookieAuth: []