openapi: 3.1.0

info:
  title: Openapi specification for cs-get-csa-title-visibility API
  description: YAML file defining an endpoint for retrieving visibility settings for csa title if the end user is an administrator
  version: 1.0.0

servers:
  - url: https://play.buerokratt.ee

paths:
  /cs-get-csa-title-visibility:
    get:
      summary: Checks whether user has administrator access and retrieves the title visibility setting for csa
      responses:
        '200':
          description: Csa title visibility retrieved successfully
          content:
            application/json:
              schema:
                type: object
        '401':
          description: Unauthorized request

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: customJwtCookie

security:
  - cookieAuth: []