openapi: 3.0.3

info:
  title: cs-get-widget-config API
  description: YAML file defining an endpoint for settings of the widget
  version: 1.0.0
  license:
    name: MIT
    url: https://github.com/buerokratt/Ruuter/blob/main/LICENSE

servers:
  - url: https://ruuter.test.buerokratt.ee

paths:
  /cs-get-widget-config:
    get:
      summary: Checks whether user is authorized and retrieves configuration of the widget
      responses:
        '200':
          description: Widget configuration retrieved successfully
          content:
            application/json:
              schema:
                type: object
        '401':
          description: Unauthorized request

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: customJwtCookie

security:
  - cookieAuth: []