openapi: 3.0.3

info:
  title: cs-get-end-user-session-length API
  description: YAML file defining an endpoint for retrieving end user session length if the request is authorized
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/license/mit/

servers:
  - url: https://ruuter.test.buerokratt.ee

paths:
  /cs-get-end-user-session-length:
    get:
      summary: Checks whether user is authorized and retrieves the end user session length
      responses:
        '200':
          description: End user session length retrieved successfully
          content:
            application/json:
              schema:
                type: object
        '401':
          description: Unauthorized request

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: customJwtCookie

security:
  - cookieAuth: []