openapi: 3.0.3

info:
  title: custom-jwt-userinfo API
  description: API for custom-jwt-userinfo
  version: 1.0.0
  license:
    name: MIT
    url: https://github.com/buerokratt/Ruuter/blob/main/LICENSE

servers:
  - url: https://ruuter.test.buerokratt.ee
    description: Main server for the database requests

paths:
  /custom-jwt-userinfo:
    post:
      summary: receive a security cookie
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"clientCustomJwtCookie"'
      responses:
        '200':
          description: custom jwt userinfo api
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      custom_jwt_userinfo:
                        example: null
                  error:
                    example: null