openapi: 3.0.3

info:
  title: estimated-waiting-time API
  description: API for calculating chat duration and estimated waiting time.
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/license/mit/

servers:
  - url: https://ruuter.test.buerokratt.ee
    description: Main server for the database requests

paths:
  /estimated-waiting-time:
    post:
      summary: Get estimated waiting time for the response
      parameters:
        - name: id
          in: query
          description: Id of the chat
          schema:
            type: string
            example: 8cfbc32a-7244-4933-8a25-14422b557ad2
      responses:
        '200':
          description: Estimated waiting time of the chat
          content:
            application/json:
              schema:
                type: object
                properties:
                  estimatedWaitingTime:
                    type: number
                    example: 0