openapi: 3.0.3

info:
  title: init-chat API
  description: API for sending the initial message to the chat-bot and receiving a chatId and response
  version: 1.0.0
  license:
    name: MIT
    url: https://github.com/buerokratt/Ruuter/blob/main/LICENSE

servers:
  - url: https://ruuter.test.buerokratt.ee
    description: Main server for the database requests

paths:
  /init-chat:
    post:
      summary: Initial user chat message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: object
                  properties:
                    chatId:
                      type: string
                      example: null
                    content:
                      type: string
                      example: tere
                    authorTimestamp:
                      type: string
                      format: date-time
                      example: '2023-05-22T05:55:44.592Z'
                    authorRole:
                      type: string
                      example: 'end-user'
                endUserTechnicalData:
                  type: object
                  properties:
                    endUserUrl:
                      type: string
                      format: uri
                      example: 'https://test.buerokratt.ee/'
                    endUserOs:
                      type: string
                      example: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36'
      responses:
        '200':
          description: Chat successfully initialized
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      get_inserted_chat:
                        type: object
                        properties:
                          id:
                            type: string
                            example: '488a4171-5e23-4735-93fa-8da8097eed8f'
                          customerSupportId:
                            type: string
                            example: meietest
                          customerSupportDisplayName:
                            type: string
                            example: Bürokratt
                          endUserId:
                            type: string
                            example: ''
                          endUserFirstName:
                            type: string
                            example: ''
                          endUserLastName:
                            type: string
                            example: ''
                          status:
                            type: string
                            example: OPEN
                          endUserOs:
                            type: string
                            example: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36'
                          endUserUrl:
                            type: string
                            format: uri
                            example: 'https://test.buerokratt.ee/'
                          lastMessage:
                            type: string
                            example: ''
                          created:
                            type: string
                            format: date-time
                            example: '2023-05-24T08:17:46.107+00:00'
                          updated:
                            type: string
                            format: date-time
                            example: '2023-05-24T08:17:46.111+00:00'
                          ended:
                            type: string
                            example: ''
                  error:
                    example: null

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: customJwtCookie

security:
  - cookieAuth: []