openapi: 3.0.3

info:
  title: post-message API
  description: API for sending a message to the chat-bot
  version: 1.0.0
  license:
    name: MIT
    url: https://github.com/buerokratt/Ruuter/blob/main/LICENSE

servers:
  - url: https://ruuter.test.buerokratt.ee
    description: Main server for the database requests

paths:
  /post-message:
    post:
      summary: Post a message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                chatId:
                  type: string
                  example: '488a4171-5e23-4735-93fa-8da8097eed8f'
                content:
                  type: string
                  example: 'Kuidas läheb?'
                authorTimestamp:
                  type: string
                  format: date-time
                  example: '2023-05-22T05:55:44.592Z'
                authorRole:
                  type: string
                  example: end-user
      responses:
        '200':
          description: Message successfully posted
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      forwarding_validation:
                        type: object
                        properties:
                          data:
                            type: object
                            properties:
                              post_message_to_bot:
                                example: null
                          error:
                            example: null
                  error:
                    example: null


components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: customJwtCookie

security:
  - cookieAuth: []