openapi: 3.0.3

info:
  title: comment-history API
  version: 1.0.0

servers:
  - url: http://play.buerokratt.ee

paths:
  /comment-history:
    get:
      summary: Retrieve chat history comment
      # TODO: Openapi 3.. does not allow requestBody for a GET operation, find an alternative (for example POST operation) way or use openapi 2.0
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                chatId:
                  type: string
                  description: The ID of the chat.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  comment:
                    type: object
                    description: Chat history comment data.
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                type: string
                example: "error: unauthorized"
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                type: string
                example: "error: not found"

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: customJwtCookie

security:
  - cookieAuth: []