openapi: 3.0.3

info:
  title: cs-set-emergency-notice API
  version: 1.0.0
  license:
    name: MIT
    url: https://github.com/buerokratt/Ruuter/blob/main/LICENSE

servers:
  - url: https://ruuter.test.buerokratt.ee

paths:
  /cs-set-emergency-notice:
    post:
      summary: Set the emergency notice details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                emergencyNoticeText:
                  type: string
                  description: The text content of the emergency notice
                  example: Example emergency notice
                emergencyNoticeStartISO:
                  type: string
                  format: date-time
                  description: The start time of the emergency notice in ISO format
                  example: 01-17-2023
                emergencyNoticeEndISO:
                  type: string
                  format: date-time
                  description: The end time of the emergency notice in ISO format
                  example: 01-18-2023
                isEmergencyNoticeVisible:
                  type: boolean
                  description: The visibility status of the emergency notice
                  example: false
      responses:
        '200':
          description: The emergency notice details were successfully set
          content:
            application/json:
              schema:
                type: object
                properties:
                  emergencyNoticeData:
                    type: array
                    items:
                      type: object
        '400':
          description: Invalid body
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: customJwtCookie

security:
  - cookieAuth: []