openapi: 3.0.3

info:
  title: cs-set-widget-config API
  version: 1.0.0
  license:
    name: MIT
    url: https://github.com/buerokratt/Ruuter/blob/main/LICENSE

servers:
  - url: https://ruuter.test.buerokratt.ee

paths:
  /cs-set-widget-config:
    post:
      summary: Set widget configuration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                widgetProactiveSeconds:
                  type: integer
                  format: int32
                widgetDisplayBubbleMessageSeconds:
                  type: integer
                  format: int32
                widgetBubbleMessageText:
                  type: string
                widgetColor:
                  type: string
                isWidgetActive:
                  type: boolean
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  widgetProactiveSeconds:
                    type: integer
                    format: int32
                  widgetDisplayBubbleMessageSeconds:
                    type: integer
                    format: int32
                  widgetBubbleMessageText:
                    type: string
                  widgetColor:
                    type: string
                  isWidgetActive:
                    type: boolean
                  created:
                    type: string
                    format: date-time
        '400':
          description: Invalid body
          content:
            text/plain:
              schema:
                type: string
                example: "error: invalid body"
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                type: string
                example: "error: unauthorized"

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: customJwtCookie

security:
  - cookieAuth: []