openapi: 3.0.3

info:
  title: cs-set-end-user-session-length API
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/license/mit/

servers:
  - url: https://ruuter.test.buerokratt.ee

paths:
  /cs-set-end-user-session-length:
    post:
      summary: Set the end user session length
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sessionLength:
                  type: integer
                  format: int32
                  description: The length of the end user session in minutes
      responses:
        '200':
          description: The end user session length was successfully set
          content:
            application/json:
              schema:
                type: object
                properties:
                  created:
                    type: string
                    format: date-time
                  key:
                    type: string
                  value:
                    type: integer
                    format: int32
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: customJwtCookie

security:
  - cookieAuth: []