openapi: 3.0.3

info:
  title: cs-set-csa-title-visibility API
  version: 1.0.0

servers:
  - url: https://ruuter.test.buerokratt.ee

paths:
  /cs-set-csa-title-visibility:
    post:
      summary: Set the visibility of the csa title
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                isVisible:
                  type: boolean
                  description: The visibility status of the csa title
      responses:
        '200':
          description: The visibility of the csa title was successfully set
          content:
            application/json:
              schema:
                type: object
                properties:
                  created:
                    type: string
                    format: date-time
                  key:
                    type: string
                  value:
                    type: boolean
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: customJwtCookie

security:
  - cookieAuth: []