openapi: 3.1.0

info:
  title: Openapi specification for cs-set-organization-working-time API
  version: 1.0.0

servers:
  - url: https://play.buerokratt.ee

paths:
  /cs-set-organization-working-time:
    post:
      summary: Set the working time of an organization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                organizationWorkingTimeStartISO:
                  type: string
                  format: date-time
                organizationWorkingTimeEndISO:
                  type: string
                  format: date-time
      responses:
        '200':
          description: Organization working time data added successfully
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Invalid body
          content:
            application/json:
              schema:
                type: object
                example: "error: invalid body"
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                type: string
                example: "error: Unauthorized"

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: customJwtCookie

security:
  - cookieAuth: []